global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  width: 200.0
  height: 200.0
  origin_x: -100.0
  origin_y: -100.0
  plugins:
    - {name: static_map,  type: "costmap_2d::StaticLayer"}
    - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,  type: "costmap_2d::InflationLayer"}